export const PERMISSIONS = {
  AUTH_LOGIN: 'AUTH.LOGIN',
  DASHBOARD_VIEW: 'DASHBOARD.VIEW',
  PROFILE_VIEW: 'PROFILE.VIEW',
  ADMIN_ACCESS: 'ADMIN.ACCESS',
  SALARY_ADVANCE_CREATE: 'SALARY_ADVANCE.CREATE',
  SALARY_ADVANCE_VIEW_SELF: 'SALARY_ADVANCE.VIEW_SELF',
  SALARY_ADVANCE_VIEW_ALL: 'SALARY_ADVANCE.VIEW_ALL',
  SALARY_ADVANCE_APPROVE_STAGE1: 'SALARY_ADVANCE.APPROVE_STAGE1',
  SALARY_ADVANCE_APPROVE_STAGE2: 'SALARY_ADVANCE.APPROVE_STAGE2',
  APPROVAL_INBOX_VIEW: 'APPROVAL.INBOX.VIEW',
  NOTIFICATION_VIEW: 'NOTIFICATION.VIEW',

  LOAN_CREATE: 'LOAN.CREATE',
  LOAN_VIEW_SELF: 'LOAN.VIEW_SELF',
  LOAN_VIEW_ALL: 'LOAN.VIEW_ALL',
  LOAN_APPROVE_STAGE1: 'LOAN.APPROVE_STAGE1',
  LOAN_APPROVE_STAGE2: 'LOAN.APPROVE_STAGE2',

} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
